version: "3"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    ports:
      - "1433:1433"
    volumes:
      - "./scripts:/scripts"
    environment:
      SA_PASSWORD: "password1234!"
      ACCEPT_EULA: "Y"
